package io.github.freshglitch.vanguardspirits.worldgen

import io.github.freshglitch.vanguardspirits.registry.ModStructures
import net.minecraft.core.BlockPos
import net.minecraft.core.Holder
import net.minecraft.core.HolderSet
import net.minecraft.core.registries.Registries
import net.minecraft.server.level.ServerLevel
import net.minecraft.world.level.ChunkPos
import net.minecraft.world.level.levelgen.structure.Structure

/**
 * Where a Guarded Ruin *is*, for anything that needs to remember something about
 * one.
 *
 * Both [RuinSeal] and [RuinHollow] key their state on the ruin's structure-start
 * chunk, and both have to agree about which chunk that is or a Sentinel dying in
 * one place and a Reliquary opening in another would write to different keys.
 * Two copies of this lookup that drifted would be exactly that bug, so there is
 * one.
 */
object Ruins {

	/**
	 * The start chunk of the Guarded Ruin containing [pos], if any.
	 *
	 * `getStructureWithPieceAt` returns [Structure]'s INVALID_START rather than
	 * null when nothing matches, so the emptiness has to be asked for. The
	 * predicate overload takes a `Predicate<Holder<Structure>>`, which lets a
	 * structure that only exists in a dynamic registry be matched without
	 * resolving it first.
	 *
	 * A ruin's two halves share one structure, so a grave on the surface and the
	 * vault thirty blocks under it both answer with the same chunk.
	 */
	fun startChunkAt(level: ServerLevel, pos: BlockPos): ChunkPos? {
		val start = level.structureManager().getStructureWithPieceAt(pos) { holder: Holder<Structure> ->
			holder.value() is GuardedRuinsStructure
		}
		return if (start.isValid) start.chunkPos else null
	}

	/**
	 * The nearest Guarded Ruin in ground nobody has uncovered yet.
	 *
	 * ## Why "unvisited" comes for free
	 *
	 * The last argument is `skipKnownStructures` -- that is the field's own name
	 * on `ExplorationMapFunction`, whose codec spells it `skip_existing_chunks`
	 * and defaults it to true, which is how a treasure map points at somewhere
	 * you have not been. Passing true here means the search steps over any
	 * candidate whose chunks are already generated.
	 *
	 * That single flag does the whole job of "the *next* ruin". The one the
	 * player is standing in is generated by definition, and so is every ruin they
	 * have already walked to, so both drop out without any need to compare
	 * positions or remember where they have been. It is also the cheaper of the
	 * two searches.
	 *
	 * The cost is that a ruin whose chunks were generated in passing -- flown
	 * over, or clipped by someone else's render distance -- is treated as visited
	 * and skipped. That is the right way round to be wrong: pointing at somewhere
	 * new that is further off beats pointing at somewhere already emptied.
	 *
	 * Null when there is nothing within [SEARCH_RINGS], which is a real answer
	 * and not a failure -- see the caller, which hands the memory back.
	 */
	fun nearestUnvisited(level: ServerLevel, from: BlockPos): BlockPos? {
		val structures = level.registryAccess().lookupOrThrow(Registries.STRUCTURE)
		val ruin = structures.get(ModStructures.GUARDED_RUINS_KEY).orElse(null) ?: return null

		val search = { origin: BlockPos ->
			level.chunkSource.generator
				.findNearestMapStructure(level, HolderSet.direct(ruin), origin, SEARCH_RINGS, true)
				?.first
		}

		// Asked twice on purpose, and the second ask is the one that answers.
		//
		// Measured across three ruins, the *first* search at a ruin returns that
		// ruin every time -- 11 blocks away in all three -- and a second search a
		// moment later returns something hundreds of blocks off. The query is
		// itself what registers the structure as known, so `skipKnownStructures`
		// has nothing to skip until it has been asked once.
		//
		// Without this a player's first feed at every new ruin is a wasted click,
		// which is precisely the feed they will make when they first meet the
		// mechanic. It costs nothing they were not already paying: before this,
		// the second feed they made by hand ran exactly the same search.
		var found = search(from)
		if (found != null && withinSameRuin(from, found)) found = search(from)

		val rejected = found != null && withinSameRuin(from, found)

		// Last line of defence, after the retry above has already had its go.
		//
		// The retry cleared this in every case measured, but it rests on a
		// mechanism nothing documents -- that asking is itself what registers a
		// structure as known -- so the answer is checked rather than trusted.
		// Ruins spread on a 24 chunk grid with a separation of 12, so no two are
		// within 192 blocks of each other, and anything this close to the asking
		// ruin *is* that ruin.
		//
		// Reaching here means declining, which costs the player nothing: the
		// memory stays in their hand.
		if (rejected) return null

		return found
	}

	private fun withinSameRuin(a: BlockPos, b: BlockPos): Boolean {
		val dx = (a.x - b.x).toDouble()
		val dz = (a.z - b.z).toDouble()
		return dx * dx + dz * dz < DISTINCT_RUIN_SQ
	}

	/**
	 * Closer than this horizontally and it is the same ruin.
	 *
	 * Comfortably under the 192 blocks that separate two of them and comfortably
	 * over the span of one, so there is no case it can decide wrongly.
	 */
	private const val DISTINCT_RUIN_SQ = 128.0 * 128.0

	/**
	 * How many **grid rings** out to look. Not chunks, and not blocks.
	 *
	 * ## The unit
	 *
	 * `getNearestGeneratedStructure` reads
	 * `RandomSpreadStructurePlacement.spacing()` and walks candidates at
	 * `base + spacing * ring`, with `ring` running `-radius..+radius` on both
	 * axes. So this counts *cells of the placement grid*, each one `spacing`
	 * chunks wide. Ruins spread on a 24 chunk grid, which makes one ring 384
	 * blocks, so the number multiplies out by 24: the 64 this started at was a
	 * reach of about **twenty four thousand blocks**.
	 *
	 * Caught only because a find came back at 657 blocks from a radius that had
	 * been written down as 512. An impossible answer is what exposed the unit; a
	 * merely surprising one would have been rationalised away.
	 *
	 * ## What it does *not* buy
	 *
	 * Not speed. Lowering this from 64 to 4 changed measured search times not at
	 * all -- cold ground cost 443, 192, 194 ms at the wide setting and 231, 160
	 * ms at the narrow one, while explored ground was 0 to 1 ms either way. The
	 * loop keeps the best distance so far and only calls the expensive
	 * `getStructureGeneratingAt` on cells nearer than it, so once something is
	 * found at ring one every outer cell is pruned by a distance compare. Walking
	 * 16,641 cells rather than 81 is nearly free because 16,560 of them are never
	 * examined.
	 *
	 * What costs is examining the handful of candidates in the first ring or two
	 * of ground the game has not assessed, which is [GuardedRuinsStructure]'s own
	 * placement check sampling columns to reject hollow sites. A first ask in
	 * unexplored terrain is about a fifth of a second and no radius avoids it.
	 *
	 * Four rings is here for **reach**, not throughput: it bounds the search that
	 * finds nothing -- the only one that really walks every ring -- and 1,536
	 * blocks is already more than double the furthest find measured. Coming back
	 * empty is a graceful answer, since the bird declines and the memory stays in
	 * the player's hand.
	 */
	private const val SEARCH_RINGS = 4
}
